### ISSUE TITLE
Octokit deprecation warning

### ISSUE THREAD

**Issue by DresdenZero** [KevinGuancheDarias/trello-to-github-board#16]
Hi,

we are getting the following error when trying to execute the last step:

``` bash
const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead FATAL: Error of type RequestError occured, message: Not Found, stack: HttpError: Not Found
    at /home/users/.nvm/versions/node/v20.15.1/lib/node_modules/trello-to-github-board/node_modules/@octokit/request/dist-node/index.js:86:21
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GithubUploaderUtil._findProject (/home/users/.nvm/versions/node/v20.15.1/lib/node_modules/trello-to-github-board/bin/utils/github-uploader.util.js:114:34)
    at async GithubUploaderUtil.uploadIssues (/home/users/.nvm/versions/node/v20.15.1/lib/node_modules/trello-to-github-board/bin/utils/github-uploader.util.js:36:31)
    at async Command.<anonymous> (/home/users/.nvm/versions/node/v20.15.1/lib/node_modules/trello-to-github-board/bin/trello-to-git-board.js:60:5)
```

We are using git version 2.34.1. 

Do you have any recommendation for us on how we could debug this error? The output file is generated fine.  We are also not sure if our map file is complete, i.e. we are not sure what is meant by "label".

Thank you a lot in advance.

**Comment by KevinGuancheDarias** [comment]
Hello @DresdenZero , this is a very old tool, I'm surprised it still works.... try with an older version of Node JS 

with nvm you can easily switch to node 14 and then go back to node 20, that should fix your issue 

Labels are github labels you can place to issues, such as "bug"

TBH I don't know if github api still works the same, as they made the new projects tab, which is way different... I hope yes, I will pray for you :wine_glass:

**Comment by KevinGuancheDarias** [comment]
Due to lack of reply, I assume it's solved
